/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PpBarChart: typeof import('./components/PpBarChart.vue')['default']
    PpFooter: typeof import('./components/PpFooter.vue')['default']
    PpHero: typeof import('./components/PpHero.vue')['default']
    PpLineChart: typeof import('./components/PpLineChart.vue')['default']
    PpNav: typeof import('./components/PpNav.vue')['default']
    PpProblem: typeof import('./components/PpProblem.vue')['default']
    PpProgression: typeof import('./components/PpProgression.vue')['default']
    PpTournois: typeof import('./components/PpTournois.vue')['default']
    PpVision: typeof import('./components/PpVision.vue')['default']
    PpWaitlist: typeof import('./components/PpWaitlist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
